version: '3.8'
services:
  genie-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./frontend:/app/frontend
    restart: always
